-- Andon veritabanı şeması.
-- scripts/seed.py her çalıştığında tabloları silip bu dosyayla yeniden kurar.
--
-- Arıza, iş emri ve bakım talebi kayıtları hatta değil makineye bağlıdır;
-- bir kaydın hattı makineler tablosu üzerinden bulunur (makineler.hat_id).
--
-- Kimlikler "BY DEFAULT" üretilir: seed kendi id'lerini yazabilir, uygulama
-- (örneğin agent'ın açtığı bakım talebi) id vermezse sıradaki değer kullanılır.

CREATE EXTENSION IF NOT EXISTS vector;

DROP TABLE IF EXISTS bakim_talepleri, is_emirleri, stok, ariza_kayitlari, makineler, hatlar;

CREATE TABLE hatlar (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad   text NOT NULL UNIQUE,
    tip  text NOT NULL CHECK (tip IN ('pres', 'kaynak', 'montaj', 'boya'))
);

CREATE TABLE makineler (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hat_id        integer NOT NULL REFERENCES hatlar (id),
    kod           text    NOT NULL UNIQUE,   -- örn. P3-HP
    ad            text    NOT NULL,          -- örn. Hidrolik Pres
    kurulum_yili  integer NOT NULL
);

CREATE TABLE ariza_kayitlari (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    makine_id   integer     NOT NULL REFERENCES makineler (id),
    baslangic   timestamptz NOT NULL,
    bitis       timestamptz,                 -- NULL: arıza hâlâ sürüyor
    ariza_tipi  text        NOT NULL
        CHECK (ariza_tipi IN ('hidrolik', 'mekanik', 'elektrik', 'sensor', 'yazilim', 'pnomatik')),
    onem        text        NOT NULL CHECK (onem IN ('dusuk', 'orta', 'yuksek')),
    hat_durdu   boolean     NOT NULL,
    aciklama    text        NOT NULL,
    CHECK (bitis IS NULL OR bitis > baslangic)
);
CREATE INDEX ON ariza_kayitlari (makine_id, baslangic);
CREATE INDEX ON ariza_kayitlari (baslangic);

CREATE TABLE stok (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parca_kodu  text    NOT NULL UNIQUE,
    ad          text    NOT NULL,
    kategori    text    NOT NULL
        CHECK (kategori IN ('hidrolik', 'mekanik', 'elektrik', 'sensor', 'pnomatik')),
    miktar      integer NOT NULL CHECK (miktar >= 0),
    min_miktar  integer NOT NULL CHECK (min_miktar >= 0),  -- altına düşünce sipariş verilmeli
    birim       text    NOT NULL,
    konum       text    NOT NULL
);

CREATE TABLE is_emirleri (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    makine_id   integer     NOT NULL REFERENCES makineler (id),
    ariza_id    integer     REFERENCES ariza_kayitlari (id),  -- periyodik bakımda NULL
    tip         text        NOT NULL CHECK (tip IN ('ariza', 'periyodik')),
    aciklama    text        NOT NULL,
    durum       text        NOT NULL CHECK (durum IN ('acik', 'devam', 'kapali')),
    atanan      text        NOT NULL,
    acilis      timestamptz NOT NULL,
    kapanis     timestamptz,
    parca_id    integer     REFERENCES stok (id),
    parca_adet  integer     CHECK (parca_adet > 0),
    CHECK ((parca_id IS NULL) = (parca_adet IS NULL)),
    CHECK ((durum = 'kapali') = (kapanis IS NOT NULL)),
    CHECK (kapanis IS NULL OR kapanis > acilis),
    CHECK ((tip = 'ariza') = (ariza_id IS NOT NULL))
);
CREATE INDEX ON is_emirleri (makine_id);
CREATE INDEX ON is_emirleri (ariza_id);

CREATE TABLE bakim_talepleri (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    makine_id  integer     NOT NULL REFERENCES makineler (id),
    aciklama   text        NOT NULL,
    oncelik    text        NOT NULL CHECK (oncelik IN ('dusuk', 'orta', 'yuksek')),
    durum      text        NOT NULL DEFAULT 'acik'
        CHECK (durum IN ('acik', 'onaylandi', 'reddedildi', 'tamamlandi')),
    olusturan  text        NOT NULL,
    olusturma  timestamptz NOT NULL DEFAULT now()
);
