-- Hata Asistanı veritabanı şeması.
-- scripts/seed.py her çalıştığında tabloları silip bu dosyayla yeniden kurar.
--
-- Arıza, iş emri ve bakım talebi kayıtları hatta değil makineye bağlıdır;
-- bir kaydın hattı makineler tablosu üzerinden bulunur (makineler.hat_id).
--
-- Kimlikler "BY DEFAULT" üretilir: seed kendi id'lerini yazabilir, uygulama
-- (örneğin agent'ın açtığı bakım talebi) id vermezse sıradaki değer kullanılır.

CREATE EXTENSION IF NOT EXISTS vector;

DROP TABLE IF EXISTS talep_fotograflari, vardiya_duruslari, vardiya_uretimi, bakim_talepleri,
                     is_emirleri, stok, ariza_kayitlari, makineler, hatlar, kullanicilar;

CREATE TABLE kullanicilar (
    id             integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kullanici_adi  text NOT NULL UNIQUE,
    ad_soyad       text NOT NULL,
    rol            text NOT NULL CHECK (rol IN ('operator', 'bakim')),
    parola_hash    text NOT NULL                  -- argon2
);

CREATE TABLE hatlar (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad               text NOT NULL UNIQUE,
    tip              text NOT NULL CHECK (tip IN ('pres', 'kaynak', 'montaj', 'boya')),
    ideal_cevrim_sn  numeric(6, 1) NOT NULL CHECK (ideal_cevrim_sn > 0)  -- parça başına, tasarım hızı
);

CREATE TABLE makineler (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hat_id        integer NOT NULL REFERENCES hatlar (id),
    kod           text    NOT NULL UNIQUE,   -- örn. P3-HP
    ad            text    NOT NULL,          -- örn. Hidrolik Pres
    kurulum_yili  integer NOT NULL
);

CREATE TABLE ariza_kayitlari (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    makine_id   integer     NOT NULL REFERENCES makineler (id),
    baslangic   timestamptz NOT NULL,
    bitis       timestamptz,                 -- NULL: arıza hâlâ sürüyor
    ariza_tipi  text        NOT NULL
        CHECK (ariza_tipi IN ('hidrolik', 'mekanik', 'elektrik', 'sensor', 'yazilim', 'pnomatik')),
    onem        text        NOT NULL CHECK (onem IN ('dusuk', 'orta', 'yuksek')),
    hat_durdu   boolean     NOT NULL,
    aciklama    text        NOT NULL,
    CHECK (bitis IS NULL OR bitis > baslangic)
);
CREATE INDEX ON ariza_kayitlari (makine_id, baslangic);
CREATE INDEX ON ariza_kayitlari (baslangic);

CREATE TABLE stok (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parca_kodu  text    NOT NULL UNIQUE,
    ad          text    NOT NULL,
    kategori    text    NOT NULL
        CHECK (kategori IN ('hidrolik', 'mekanik', 'elektrik', 'sensor', 'pnomatik')),
    miktar      integer NOT NULL CHECK (miktar >= 0),
    min_miktar  integer NOT NULL CHECK (min_miktar >= 0),  -- altına düşünce sipariş verilmeli
    birim       text    NOT NULL,
    konum       text    NOT NULL
);

CREATE TABLE is_emirleri (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    makine_id   integer     NOT NULL REFERENCES makineler (id),
    ariza_id    integer     REFERENCES ariza_kayitlari (id),  -- periyodik bakımda NULL
    tip         text        NOT NULL CHECK (tip IN ('ariza', 'periyodik')),
    aciklama    text        NOT NULL,
    durum       text        NOT NULL CHECK (durum IN ('acik', 'devam', 'kapali')),
    atanan      text        NOT NULL,
    acilis      timestamptz NOT NULL,
    kapanis     timestamptz,
    parca_id    integer     REFERENCES stok (id),
    parca_adet  integer     CHECK (parca_adet > 0),
    CHECK ((parca_id IS NULL) = (parca_adet IS NULL)),
    CHECK ((durum = 'kapali') = (kapanis IS NOT NULL)),
    CHECK (kapanis IS NULL OR kapanis > acilis),
    CHECK ((tip = 'ariza') = (ariza_id IS NOT NULL))
);
CREATE INDEX ON is_emirleri (makine_id);
CREATE INDEX ON is_emirleri (ariza_id);

-- Agent'ın her isteği: token, maliyet, süre ve çağrılan araçlar.
-- Yukarıdaki DROP listesinde yok: seed'i yeniden çalıştırmak bu kayıtları silmez.
CREATE TABLE IF NOT EXISTS llm_istekleri (
    id              integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    zaman           timestamptz NOT NULL DEFAULT now(),
    kullanici       text        NOT NULL,
    saglayici       text        NOT NULL,
    model           text        NOT NULL,
    soru            text        NOT NULL,
    cevap           text,
    arac_cagrilari  jsonb       NOT NULL DEFAULT '[]',
    adim_sayisi     integer     NOT NULL,
    girdi_token     integer     NOT NULL,
    cikti_token     integer     NOT NULL,
    maliyet_usd     numeric(12, 6),                      -- fiyatı bilinmeyen modelde NULL
    sure_ms         integer     NOT NULL,
    hata            text
);

-- Hattın bir vardiyadaki üretim özeti; bir MES'in (ör. Verimot) vardiya sonunda verdiği kayıt.
-- Planlı süre = 480 dk vardiya - 30 dk mola - hattaki planlı (periyodik) bakım.
CREATE TABLE vardiya_uretimi (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hat_id          integer     NOT NULL REFERENCES hatlar (id),
    vardiya         smallint    NOT NULL CHECK (vardiya IN (1, 2, 3)),  -- 07-15, 15-23, 23-07
    baslangic       timestamptz NOT NULL,
    bitis           timestamptz NOT NULL,
    planli_sure_dk  integer     NOT NULL CHECK (planli_sure_dk > 0),
    toplam_adet     integer     NOT NULL CHECK (toplam_adet >= 0),
    hurda_adet      integer     NOT NULL CHECK (hurda_adet >= 0),
    UNIQUE (hat_id, baslangic),
    CHECK (bitis > baslangic),
    CHECK (hurda_adet <= toplam_adet)
);
CREATE INDEX ON vardiya_uretimi (baslangic);

-- Vardiyanın planlı süresi içindeki duruşlar (kullanılabilirlik kaybı). Nedenler:
--   ariza          hattı durduran arıza; tipi ve makinesi arıza kaydından gelir, ayrıca tutulmaz
--   urun_degisimi  kalıp, fikstür, renk ya da model değişimi
--   malzeme_bekleme
-- Aynı anda iki arıza hattı durdurduysa çakışan dakikalar önce başlayan arızaya yazılır;
-- böylece bir vardiyanın duruşlarının toplamı hattın gerçekten durduğu süreye eşittir.
CREATE TABLE vardiya_duruslari (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vardiya_id  integer NOT NULL REFERENCES vardiya_uretimi (id),
    neden       text    NOT NULL CHECK (neden IN ('ariza', 'urun_degisimi', 'malzeme_bekleme')),
    ariza_id    integer REFERENCES ariza_kayitlari (id),
    sure_dk     integer NOT NULL CHECK (sure_dk > 0),
    CHECK ((neden = 'ariza') = (ariza_id IS NOT NULL))
);
CREATE INDEX ON vardiya_duruslari (vardiya_id);
CREATE UNIQUE INDEX ON vardiya_duruslari (vardiya_id, ariza_id) WHERE ariza_id IS NOT NULL;

CREATE TABLE bakim_talepleri (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    makine_id  integer     NOT NULL REFERENCES makineler (id),
    aciklama   text        NOT NULL,
    oncelik    text        NOT NULL CHECK (oncelik IN ('dusuk', 'orta', 'yuksek')),
    durum      text        NOT NULL DEFAULT 'acik'
        CHECK (durum IN ('acik', 'onaylandi', 'reddedildi', 'tamamlandi')),
    olusturan  text        NOT NULL,
    olusturma  timestamptz NOT NULL DEFAULT now()
);
